import type { Metadata } from "next"
import Link from "next/link"
import BusinessPage from "../components/BusinessPage"
const title = "システム・商品・サービス | 積み上げログ"
const description = "Webサイト制作、業務支援システム、自動化、技術相談、IT転職・副業・資格などのキャリア・学習支援を個別見積もりで提供します。"
export const metadata: Metadata = { title, description, alternates: { canonical: "/services" }, openGraph: { title, description, type: "website", url: "/services", images: ["/og.png"] }, twitter: { card: "summary_large_image", title, description, images: ["/og.png"] } }
const services = [{title:"Webサイト・LP制作",text:"目的、読者、検索意図を整理し、スマートフォン対応のサイトを制作します。",deliver:"情報設計／実装／SEO基本設定／公開支援"},{title:"業務支援システム開発",text:"繰り返し作業や情報管理を、使いやすいWebアプリへ置き換えます。",deliver:"要件整理／画面設計／開発／操作説明"},{title:"既存サイト改善・自動化",text:"表示、導線、更新作業、GitHub Actionsなどの運用課題を改善します。",deliver:"現状調査／改善案／実装／検証"},{title:"技術相談・調査",text:"実装方針、サービス選定、エラー原因を調査し、次の行動を整理します。",deliver:"相談記録／調査結果／推奨手順"},{title:"キャリア・学習支援",text:"IT転職、副業・フリーランス、スクール、資格について、目的と現在地を整理して次の行動を提案します。",deliver:"経験整理／ポートフォリオ確認／比較条件／学習計画"}]
const serviceSchema = { "@context": "https://schema.org", "@type": "Service", provider: { "@type": "Organization", name: "積み上げログ", url: "https://syunnjack.dev" }, name: "システム・商品・サービス", areaServed: "JP", hasOfferCatalog: { "@type": "OfferCatalog", name: "提供サービス一覧", itemListElement: services.map((s) => ({ "@type": "Offer", itemOffered: { "@type": "Service", name: s.title, description: s.text } })) } }
const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "ホーム", item: "https://syunnjack.dev" }, { "@type": "ListItem", position: 2, name: "サービス", item: "https://syunnjack.dev/services" }] }
export default function ServicesPage() { return <BusinessPage eyebrow="PRODUCTS / SERVICES" title="システム・商品・サービス" lead="作って終わりではなく、目的を達成し、継続して使える状態までを意識して支援します。" schemas={[serviceSchema, breadcrumbSchema]}><section className="business-section"><div className="service-grid">{services.map((s, i) => <article key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.text}</p><strong>主な納品・支援内容</strong><small>{s.deliver}</small><Link href={`/estimate?service=${encodeURIComponent(s.title)}`}>このサービスを相談する →</Link></article>)}</div><div className="process"><h2>ご依頼の流れ</h2><ol><li><strong>相談</strong><span>目的と課題を確認</span></li><li><strong>提案・見積もり</strong><span>範囲、期間、費用を提示</span></li><li><strong>制作・確認</strong><span>途中経過を共有して調整</span></li><li><strong>納品・振り返り</strong><span>使い方と改善を整理</span></li></ol></div></section></BusinessPage> }
